# Generated by Django 5.0.2 on 2024-02-26 01:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0002_rename_info_info1"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Info1",
            new_name="Info",
        ),
    ]
