# Generated by Django 5.0.2 on 2024-02-27 10:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("annonce", "0002_annonce"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="annonce",
            name="author",
        ),
    ]
