# Generated by Django 5.0.2 on 2024-02-27 15:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("annonce", "0006_commentaire"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Commentaire",
        ),
    ]
