# Generated by Django 5.0.2 on 2024-02-25 23:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maxt", "0002_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="first",
            name="titre",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="title",
            name="titre",
            field=models.CharField(max_length=50),
        ),
    ]
