# Generated by Django 5.0.2 on 2024-02-26 00:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maxt", "0003_alter_first_titre_alter_title_titre"),
    ]

    operations = [
        migrations.CreateModel(
            name="Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.TextField()),
                ("mail", models.EmailField(max_length=254)),
                ("adresse", models.TextField()),
            ],
        ),
    ]
